#!/bin/bash
# DO NOT EDIT THIS FILE !!!
# DO NOT EDIT THIS FILE !!!
# DO NOT EDIT THIS FILE !!!
# DO NOT EDIT THIS FILE !!!
# DO NOT EDIT THIS FILE !!!
# DO NOT EDIT THIS FILE !!!
# DO NOT EDIT THIS FILE !!!
# This file is used to run the FastAPI application.
# It is automatically generated by the aime_create_fastapi_app command.

set -ex
cd `dirname $0`

WORK_DIR="/tmp/faas_work"
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR"
cp -r /opt/bytefaas/* "$WORK_DIR/"
cd "$WORK_DIR"

export RUNTIME_LOGDIR=/opt/tiger/toutiao/log
export PYTHONPATH=./site-packages 

exec python3 ./main.py
